version: '3.1'
services:
    web:
        image: dtr.clovett.dtcntr.net/engineering/demo-app
        deploy:
            mode: replicated
            replicas: 2
        healthcheck:
            interval: 10s
            retries: 3
        ports:
            - 5000:5000

networks:
    backend:
